### ISSUE TITLE
Better Target and SmoothGraphics

### ISSUE THREAD

**Issue by dev7355608** [sPOiDar/fvtt-module-better-target#6]
Hi!

v9 is coming with the graphics-smooth lib, but it is still buggy. For example, holes in shapes other than polygons are not working. PV has included graphics-smooth for a while now, and I actually included a fix for this hole problem, but there is still the issue that the inner outline (the outline of the hole) is not rendered. So I recommend to not use holes at all:

```js
this.target.beginFill(0x000000, 0.0).lineStyle(stroke, 0xc72121)
	.drawCircle(hmid, vmid, (size / 2) - padding)
	.lineStyle(1, 0x000000)
	.drawCircle(hmid, vmid, (size / 2) - padding + stroke / 2)
	.drawCircle(hmid, vmid, (size / 2) - padding - stroke / 2)
	.endFill()
	.beginFill(0xc72121, 1.0).lineStyle(1, 0x000000)
	.drawRoundedRect(hmid - (stroke / 2), vmid - stroke - (padding / 2) - crossLen, stroke, crossLen, stroke / 2 * 0.99)
	.drawRoundedRect(hmid - (stroke / 2), vmid + (padding * 1.5) - stroke, stroke, crossLen, stroke / 2 * 0.99)
	.drawRoundedRect(hmid - stroke - (padding / 2) - crossLen, vmid - (stroke / 2), crossLen, stroke, stroke / 2 * 0.99)
	.drawRoundedRect(hmid + (padding * 1.5) - stroke, vmid - (stroke / 2), crossLen, stroke, stroke / 2 * 0.99)
	.endFill();
```

I also noticed that the radius parameter of `drawRoundedRect` is missing (by default it is 20). You might ask why used `stroke / 2 * 0.99` instead `stroke / 2`: well, it looks like there's another bug in graphics-smooth that causes the outline to be rendered incorrectly; there appears a gap in the outline if the radius is larger or equal to the maximum possible radius.

![image](https://user-images.githubusercontent.com/31905376/139582909-268e973f-0520-4d9b-ac19-ead25377472b.png)

**Comment by dev7355608** [comment]
graphics-smooth just released a fix for the gap issue (v0.0.17). So assuming v9 comes with the latest version of graphics-smooth, you don't need to do `* 0.99`.

**Comment by sPOiDar** [comment]
Oh boy, fun! Thank you for reporting this - I've not started in on v9 testing yet, though I really should get around to it soon as I know some of my mods will certainly have problems.

Hole punching seems to have been a recurring problem in PIXI/earcut, so avoiding it is probably a sensible idea. I'll try and find some time to do a little testing this week, but the results certainly look pretty convincing, thanks again.

**Comment by sPOiDar** [comment]
I did some testing of the proposed change, and I couldn't reproduce your working results in either v0.8.9, or v0.9.226 using the provided code, however I worked out an alternative using layered lines based on the stroke width.
