### ISSUE TITLE
Mod Conflict: Border Control

### ISSUE THREAD

**Issue by Crowguard** [sPOiDar/fvtt-module-better-target#7]
LibWrapperAlreadyOverriddenError: Conflict detected between module Better Target and module Border Control.

This is not a libWrapper bug.

Find information about these packages here:

    Module Better Target: https://github.com/sPOiDar/fvtt-module-better-target
    Module Border Control: https://github.com/kandashi/Border-Control

Report this conflict here:

    Module Better Target: https://github.com/sPOiDar/fvtt-module-better-target/issues

Ask the community for support:

    FoundryVTT Discord's #modules-troubleshooting channel: https://discord.gg/foundryvtt
    FoundryVTT Reddit: https://www.reddit.com/r/FoundryVTT

== Technical Details:
Detected by libWrapper.
Package IDs= better-target, Border-Control
Error= Failed to wrap 'Token.prototype._refreshTarget' for module better-target with type OVERRIDE. An OVERRIDE wrapper for the same method has already been registered by module Border-Control.

[Detected 1 package: better-target]
LibWrapperError libWrapper-base_errors.js:19
LibWrapperAlreadyOverriddenError libWrapper-api_errors.js:91
register libWrapper-api.js:555
better_target.js:10
_call foundry.js:294
callAll foundry.js:253
setupGame foundry.js:5567
foundry.js:319:30
onError foundry.js:319
call_wrapped libWrapper-wrapper.js:511
listeners.js:134
onError#0 libWrapper-wrapper.js:187
_call foundry.js:298
callAll foundry.js:253
setupGame foundry.js:5567

**Comment by sPOiDar** [comment]
Border Control does indeed have conflicting functionality, however it has a setting that you can use to disable replacing the target indicator, that will avoid the conflict.
